name: "GitHub Action: Simple Release"
description: "GitHub Action for creating simple GitHub Releases"
author: "Nicholas Valentinus"
branding:
  icon: package
  color: gray-dark

inputs:
  tag:
    description: "Release tag (also title)"
    required: true
  desc:
    description: "Release description"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_DESC: ${{ inputs.desc }}